# Resident vs registered

- Used patient's LSOA to map up to ICB and LA
- Used patient's registered GP to map up to PCN

# Population data

## LSOA to ICB and LA

- Mapped LSOA11 codes to LSOA21 then mapped this to ICB24 / LA24
- Even though some LSOA11 mapped to multiple LSOA21, they still only mapped to one ICB
- But 4 LSOA11 codes mapped to multiple LA:

```{r}
#| eval: false
targets::tar_read(lsoa_population) |> 
  dplyr::rename(lsoa11cd = area_code) |>
  dplyr::left_join(targets::tar_read(lsoa11_to_lsoa_21), by = "lsoa11cd") |>
  dplyr::left_join(targets::tar_read(lsoa_to_higher_geographies) |>
                     dplyr::select(-geometry),
                   by = "lsoa21cd") |>
  dplyr::summarise(la = paste(lad24cd, collapse = ","),
                   .by = lsoa11cd) |>
  tidyr::separate(la, sep = ",", into = c("a", "b", "c")) |>
  dplyr::filter(a != b | a != c | b != c)
```

- So method was to divide the LSOA11 population by the number of LA it mapped to before calculating the LA population size
- For recent years where LSOA population estimates were not yet available, the latest available year's data was used


- For APCE indicators, LSOA11 codes were used, since more populated in the data
  - There were no rows in `[Reporting_MESH_APC].[APCE_Core_Monthly_Snapshot]` where `Der_Postcode_LSOA_2021_Code` was provided but `Der_Postcode_LSOA_2011_Code` was not:
  
```{sql}
#| eval: false
SELECT
	Der_financial_year,	
	COUNT(*)

FROM [Reporting_MESH_APC].[APCE_Core_Monthly_Snapshot]

WHERE 
  Der_Postcode_LSOA_2021_Code IS NOT NULL AND 
  Der_Postcode_LSOA_2011_Code IS NULL 

GROUP BY Der_financial_year

ORDER BY Der_financial_year
```
  

## GP to PCN

- PCN populations were calculated by aggregating GP populations up.
- For GP populations there were two data sources. The older one (from 2013-04-01 to 2017-01-01) had the data quarterly. This was transformed to monthly by using the data for the first month in a quarter for all months in that quarter. From 2017-04-01, the second data source at monthly level was used instead.

# Calculating age, sex and IMD quintile standardised rates

The {pheindicatormethods} R package was used to calculate standardised rates. The numerator, denominator and standard population we used for this are outlined below. 

- Numerator: counts of admissions by LSOA, 5-year age band, sex and IMD quintile grouped to ICB, LA or PCN level.
- Denominator: LSOA population estimates from ONS (and UKHF) by 5-year age band, sex and IMD quintile grouped to ICB, LA or PCN level. 
- Standard population: The revised European Standard Population (ESP) 2013 from [ONS](httpswebarchive.nationalarchives.gov.ukukgwa20160106020035httpwww.ons.gov.ukonsguide-methoduser-guidancehealth-and-life-eventsrevised-european-standard-population-2013--2013-esp-index.html). As this is only factored by age and sex, we estimated the distribution of the notional ESP figures by IMD quintiles by splitting the population equally between the quintiles.

For analyses, LSOA codes were transformed into 2021 LSOA codes before aggregating up to the latest ICB, LA and PCN groups. But since IMD can change over time, IMD quintiles were calculated by using recent IMDs according to the table below:

| Dates of activity | Year of IMD |
| --- | --- |
| 2008-04-01 - 2010-03-31 | 2007* |
| 2010-04-01 - 2015-03-31 | 2010* |
| 2015-04-01 - 2019-03-31 | 2015 |
| 2019-04-01 - 2015-03-31 | 2019 |
| 2025-04-01 - current | 2025 |

*This is the ideal and still working on it, but currently using 2015 since not got IMD quintile data yet for these years.

In less than 0.2% of cases there was no IMD quintile information available and so the latest available IMD year was used instead for that LSOA.

# Identifying admissions of older people with frailty

- Identified emergency admissions of patients aged 75+ (to match CPMA definition) and the discharge month
- Then got the patients' prior admissions from within 2 years and their primary diagnosis
- Then calculated weighted sum using `frailty_risk_scores.csv` and classed scores >15 as high and >5 as intermediate

# AE frequent attenders

- Someone who has attended AE 3 times or more - according to CPMA defs?
- Source data was at 2011 lsoa level, so had to map to 2021 lsoa codes. For the few lsoa11 that split into multiple lsoa21, number of frequent attenders was split equally between the lsoa21 codes.

